### ISSUE TITLE
Question regarding code release timeline

### ISSUE THREAD

**Issue by hubert0527** [yikaiw/Vidu4D#1]
Dear authors,

Thanks for sharing your amazing work and planning to release the codes!
May I gently ask when the codes/models are tentative to release, like within a few weeks or after paper acceptance?
Sincerely thanks!

Best,
Hubert

**Comment by yikaiw** [comment]
Thank you for your interest. Our code will be released before the acceptance of the corresponding paper, or possibly sooner.

**Comment by yikaiw** [comment]
We appreciate your interest. Our code has been released.
